# docker run -itd --name mi-mysql 
#   -v mi-mysql-vol:/var/lib/mysql 
#   -e MYSQL_ROOT_PASSWORD=root 
#   --net mi-mysql-red mysql:latest

# docker run -d --name mi-phpmyadmin 
#   --net mi-mysql-red 
#   -v mi-mysql-vol 
#   --link mi-mysql:db 
#   -p 8080:80 phpmyadmin

services:
  mysql:
    container_name: mi-mysql
    image: mysql:latest
    volumes:
      - mi-mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mi-mysql-red
    stdin_open: true

  mi-phpmyadmin:
    container_name: mi-phpmyadmin
    image: phpmyadmin
    networks:
      - mi-mysql-red
    links:
      - mysql:db
    ports:
      - 8080:80

volumes:
  mi-mysql-vol:


networks:
  mi-mysql-red:
    ipam:
      config:
        - subnet: 172.25.0.0/16
